# Generated by Django 4.2 on 2024-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_solicitudarriendo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(default='correo@correo.cl', max_length=254, unique=True),
        ),
    ]
